"""Assistant-shaped tools (patch 0002): a session briefing and task
operations that format and place task lines server-side, so agents don't
rebuild these from generic reads and whole-note rewrites. Semantic choices
(which file, which section, what counts as done) stay with the agent."""

from __future__ import annotations

import re
from collections.abc import Callable
from datetime import date, timedelta
from difflib import SequenceMatcher

from ..config import get_config
from ..domain.index import VaultIndex
from ..storage.locking import acquire_lock
from ..storage.revisions import read_text_for_update, revision_result
from .query import get_tasks, query_notes
from .read import read_note_content
from .write import _require_note_path, _storage, locate_section

TASK_FILES = ("Todo.md", "Backlog.md", "Follow-ups.md")
# Where active commitments live. Dated tasks anywhere else (reference pages, old event
# checklists) are not planning input: the briefing lists them apart as dated_elsewhere.
PLANNING_FILES = (*TASK_FILES, "lists/creative-projects.md")
# Generated by the google-sync runner from Google Calendar; one note per event.
EVENTS_FOLDER = "calendar/events"
TODO_FILE = "Todo.md"
QUESTIONS_FILE = "Questions.md"
DONE_SECTION = "Done"

_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
_TASK_LINE_RE = re.compile(r"^(\s*)- \[( |x|X)\] (.*)$")
_MARKERS = ("➕", "📅", "✅", "⏫", "🔽", "🔼", "🔁")
_MARKER_TAIL_RE = re.compile(r"\s*(?:[➕📅✅⏫🔽🔼🔁]|\d{4}-\d{2}-\d{2}|#calendar)")
_MAX_TEXT = 200


# ── Briefing ─────────────────────────────────────────────────────────────────


_ADDED_RE = re.compile(r"\s*➕\s*\d{4}-\d{2}-\d{2}")


def _compact(task: dict) -> dict:
    out = {"text": _ADDED_RE.sub("", task["text"])[:_MAX_TEXT], "source": task["source"]}
    for key in ("section", "due", "priority"):
        if task.get(key):
            out[key] = task[key]
    return out


def _events(index: VaultIndex, start: date, stop: date) -> list[dict]:
    """Calendar events with start in [start, stop), skipping ones deleted in Google."""
    notes = query_notes(
        index, folder=EVENTS_FOLDER, limit=100,
        frontmatter_filter={"date": {"$gte": start.isoformat(), "$lt": stop.isoformat()}},
    )
    out = []
    for n in notes:
        fm = n["frontmatter"]
        if "/orphaned/" in n["path"] or fm.get("status") == "cancelled":
            continue
        event = {"title": str(fm.get("title") or n["title"])[:_MAX_TEXT], "start": _iso(fm.get("date")), "path": n["path"]}
        for key in ("end", "location"):
            if fm.get(key):
                event[key] = _iso(fm[key]) if key == "end" else str(fm[key])[:_MAX_TEXT]
        out.append(event)
    return sorted(out, key=lambda e: e["start"])


def _iso(value) -> str:
    return value.isoformat() if hasattr(value, "isoformat") else str(value)


def get_briefing(index: VaultIndex, today: date | None = None, horizon_days: int = 7, recent: int = 10) -> dict:
    today = today or date.today()
    iso = today.isoformat()
    horizon = (today + timedelta(days=horizon_days)).isoformat()
    open_tasks = get_tasks(index)
    questions = [t for t in open_tasks if t["source"] == QUESTIONS_FILE]
    tasks = [t for t in open_tasks if t["source"] != QUESTIONS_FILE]

    out: dict = {"date": iso}
    out["today"] = [_compact(t) for t in tasks if t["source"] == TODO_FILE and t.get("section") == "Today"]
    out["waiting"] = [_compact(t) for t in tasks if t["source"] == TODO_FILE and t.get("section") == "Waiting"]
    planned = [t for t in tasks if t["source"] in PLANNING_FILES]
    out["overdue"] = [_compact(t) for t in planned if t["due"] and t["due"] < iso]
    out["due_soon"] = [_compact(t) for t in planned if t["due"] and iso <= t["due"] <= horizon]
    stray = [t for t in tasks if t["due"] and t["source"] not in PLANNING_FILES]
    out["dated_elsewhere"] = [_compact(t) for t in sorted(stray, key=lambda t: t["due"])[:5]]
    out["events"] = _events(index, today, today + timedelta(days=2))
    out["open_questions"] = [t["text"][:160] for t in questions]
    out["open_task_counts"] = {
        name: sum(1 for t in tasks if t["source"] == name) for name in TASK_FILES
    }
    out["open_task_counts"]["elsewhere"] = sum(1 for t in tasks if t["source"] not in TASK_FILES)
    try:
        from .audit import get_audit_log

        out["recent_changes"] = [
            {
                "time": (e.get("timestamp") or "")[:16],
                "tool": e.get("tool"),
                "path": e.get("path"),
                "by": e.get("login") or e.get("client"),
            }
            for e in get_audit_log(limit=recent)
        ]
    except Exception:
        out["recent_changes"] = []
    return out


# ── Task lines ───────────────────────────────────────────────────────────────


def format_task(
    text: str,
    due: str | None = None,
    priority: str | None = None,
    calendar: bool = False,
    added: str | None = None,
) -> str:
    """`- [ ] text #calendar ⏫ 📅 due ➕ added`, only the parts that apply."""
    text = " ".join(text.split())
    if not text:
        raise ValueError("Task text is empty.")
    if text.startswith("- [") or any(m in text for m in _MARKERS):
        raise ValueError(
            "Pass the plain task text. Dates and priority go in due/priority; the server adds the markers."
        )
    if due and not _DATE_RE.match(due):
        raise ValueError(f"due must be YYYY-MM-DD, got {due!r}")
    if priority not in (None, "high", "low"):
        raise ValueError(f"priority must be 'high', 'low' or null, got {priority!r}")
    parts = ["- [ ]", text]
    if calendar and "#calendar" not in text:
        parts.append("#calendar")
    if priority == "high":
        parts.append("⏫")
    elif priority == "low":
        parts.append("🔽")
    if due:
        parts.append(f"📅 {due}")
    parts.append(f"➕ {added or date.today().isoformat()}")
    return " ".join(parts)


def _norm(text: str) -> str:
    text = _MARKER_TAIL_RE.sub(" ", text)
    return " ".join(re.sub(r"[^\w]+", " ", text.casefold()).split())


def find_similar_tasks(
    index: VaultIndex, text: str, also: str | None = None, limit: int = 5, threshold: float = 0.8
) -> list[dict]:
    """Near-duplicates among open tasks in the task files (and `also`, the
    target note). Checklists on living pages are deliberately left out:
    reusable lists repeat items by design."""
    wanted = _norm(text)
    if not wanted:
        return []
    scored = []
    scopes = dict.fromkeys([*TASK_FILES, *([also] if also else [])])
    pool = [t for scope in scopes for t in get_tasks(index, path=scope)]
    for task in pool:
        other = _norm(task["text"])
        if not other:
            continue
        ratio = SequenceMatcher(None, wanted, other).ratio()
        contained = len(wanted) >= 12 and len(other) >= 12 and (wanted in other or other in wanted)
        if ratio >= threshold or contained:
            scored.append((max(ratio, 0.9 if contained else 0), task))
    scored.sort(key=lambda pair: -pair[0])
    return [
        {**_compact(task), "line": task["line"], "similarity": round(score, 2)}
        for score, task in scored[:limit]
    ]


def _section_span(raw: str, section: str, occurrence: int | None) -> tuple[list[str], int, int]:
    """(lines, heading index, index of the first line after the section)."""
    loc = locate_section(raw, section, occurrence)
    lines = raw.split("\n")
    heading = loc["line"] - 1
    end = len(lines) if loc["body_end"] >= len(raw) else raw.count("\n", 0, loc["body_end"])
    return lines, heading, end


def insert_in_section(
    raw: str, section: str, block: list[str], occurrence: int | None = None, position: str = "end"
) -> str:
    """Insert lines into a section without adding blank lines inside a list:
    after its last non-blank line (end) or before its first (top)."""
    lines, heading, end = _section_span(raw, section, occurrence)
    body = [i for i in range(heading + 1, end) if lines[i].strip()]
    if not body:
        lines[heading + 1:end] = ["", *block] + ([""] if end < len(lines) else [])
    elif position == "top":
        lines[body[0]:body[0]] = block
    else:
        lines[body[-1] + 1:body[-1] + 1] = block
    return "\n".join(lines)


def _task_block(lines: list[str], start: int) -> int:
    """Index after the task at `start` and its more-indented child lines."""
    indent = len(lines[start]) - len(lines[start].lstrip())
    end = start + 1
    while end < len(lines):
        line = lines[end]
        if line.strip() and len(line) - len(line.lstrip()) <= indent:
            break
        if not line.strip():
            # A blank line ends the block unless an indented child follows it.
            nxt = end + 1
            if nxt >= len(lines) or len(lines[nxt]) - len(lines[nxt].lstrip()) <= indent:
                break
        end += 1
    return end


def find_open_task(raw: str, task: str, path: str) -> tuple[list[str], int, int]:
    """Locate one open task by exact text or unique substring. Errors list
    candidates, so the caller can retry with a more specific text."""
    lines = raw.split("\n")
    wanted = " ".join(task.split())
    if wanted.startswith("- [ ] "):
        wanted = wanted[6:]
    exact, partial = [], []
    for i, line in enumerate(lines):
        m = _TASK_LINE_RE.match(line)
        if not m or m.group(2) != " ":
            continue
        body = " ".join(m.group(3).split())
        if body == wanted or _norm(body) == _norm(wanted):
            exact.append(i)
        elif wanted.casefold() in body.casefold():
            partial.append(i)
    hits = exact or partial
    if not hits:
        open_lines = [
            line.strip()[:120] for line in lines
            if (m := _TASK_LINE_RE.match(line)) and m.group(2) == " "
        ]
        raise ValueError(
            f"No open task matching {task!r} in {path!r}. Open tasks there: "
            + ("; ".join(open_lines[:15]) or "(none)")
        )
    if len(hits) > 1:
        raise ValueError(
            f"{len(hits)} open tasks in {path!r} match {task!r}; pass more of the text. Matches: "
            + "; ".join(f"line {i + 1}: {lines[i].strip()[:120]}" for i in hits[:10])
        )
    start = hits[0]
    return lines, start, _task_block(lines, start)


def _update_note(
    path: str,
    expected_revision: str | None,
    mutate: Callable[[str], str],
    index: VaultIndex | None,
    status: str,
) -> dict:
    _require_note_path(path)
    storage = _storage()
    path = storage.resolve_write(path).relative
    lock = acquire_lock(path, lock_path=get_config().lock_path)
    try:
        raw, current = read_text_for_update(storage, path, expected_revision)
        new = mutate(raw)
        if new == raw:
            return {"path": path, "status": "unchanged", "revision": current}
        revision = storage.write_text_atomic(path, new, expected_revision=current)
    finally:
        lock.release()
    if index is not None:
        index.update(path)
    return revision_result({"path": path, "status": status}, revision)


def add_task(
    index: VaultIndex,
    path: str,
    section: str,
    text: str,
    due: str | None = None,
    priority: str | None = None,
    calendar: bool = False,
    force: bool = False,
    expected_revision: str | None = None,
    occurrence: int | None = None,
    added: str | None = None,
) -> dict:
    if added and not _DATE_RE.match(added):
        raise ValueError(f"added must be YYYY-MM-DD, got {added!r}")
    line = format_task(text, due=due, priority=priority, calendar=calendar, added=added)
    if not force:
        similar = find_similar_tasks(index, text, also=path)
        if similar:
            return {
                "path": path,
                "status": "duplicate_suspected",
                "task": line,
                "candidates": similar,
                "hint": "Nothing written. Update or close the existing task, or pass force=true to add anyway.",
            }
    result = _update_note(
        path,
        expected_revision,
        lambda raw: insert_in_section(raw, section, [line], occurrence),
        index,
        "task_added",
    )
    result["task"] = line
    return result


def complete_task(
    index: VaultIndex,
    path: str,
    task: str,
    done_date: str | None = None,
    expected_revision: str | None = None,
) -> dict:
    done_date = done_date or date.today().isoformat()
    if not _DATE_RE.match(done_date):
        raise ValueError(f"done_date must be YYYY-MM-DD, got {done_date!r}")
    closed: list[str] = []

    def mutate(raw: str) -> str:
        lines, start, end = find_open_task(raw, task, path)
        block = lines[start:end]
        first = re.sub(r"\s*✅\s*\d{4}-\d{2}-\d{2}", "", block[0].rstrip())
        block[0] = first.replace("- [ ]", "- [x]", 1) + f" ✅ {done_date}"
        closed.append(block[0].strip())
        rest = "\n".join(lines[:start] + lines[end:])
        if any(text == DONE_SECTION for _, text in _headings(rest)):
            return insert_in_section(rest, DONE_SECTION, block, occurrence=-1, position="top")
        return rest.rstrip("\n") + f"\n\n## {DONE_SECTION}\n\n" + "\n".join(block) + "\n"

    result = _update_note(path, expected_revision, mutate, index, "task_completed")
    result["task"] = closed[0] if closed else None
    result["reminder"] = (
        "If this task carries a durable fact (a purchase, place, event, person, project step), "
        "record it in its standing page."
    )
    return result


def move_task(
    index: VaultIndex,
    path: str,
    task: str,
    to_path: str,
    to_section: str,
    expected_revision: str | None = None,
    to_expected_revision: str | None = None,
    to_occurrence: int | None = None,
) -> dict:
    """Move one open task (and its indented children) unchanged. Across
    files the target is written first: a failure leaves a duplicate, never
    a lost task."""
    storage = _storage()
    source = storage.resolve_write(path).relative
    target = storage.resolve_write(to_path).relative
    if source == target:
        def mutate(raw: str) -> str:
            lines, start, end = find_open_task(raw, task, source)
            block = lines[start:end]
            rest = "\n".join(lines[:start] + lines[end:])
            return insert_in_section(rest, to_section, block, to_occurrence)

        result = _update_note(source, expected_revision, mutate, index, "task_moved")
        result["to_path"] = target
        return result

    raw = storage.read_text(source)
    lines, start, end = find_open_task(raw, task, source)
    block = lines[start:end]
    moved = _update_note(
        target,
        to_expected_revision,
        lambda text: insert_in_section(text, to_section, block, to_occurrence),
        index,
        "task_moved",
    )

    def remove(text: str) -> str:
        cur_lines, cur_start, cur_end = find_open_task(text, task, source)
        return "\n".join(cur_lines[:cur_start] + cur_lines[cur_end:])

    removed = _update_note(source, expected_revision, remove, index, "task_moved")
    return {
        "path": source,
        "status": "task_moved",
        "revision": removed.get("revision"),
        "to_path": target,
        "to_revision": moved.get("revision"),
        "task": block[0].strip(),
    }


def _headings(raw: str) -> list[tuple[int, str]]:
    from .write import list_headings

    return [(m.start(), text) for m, text in list_headings(raw)]


# ── Entities ─────────────────────────────────────────────────────────────────


def list_entities(
    index: VaultIndex,
    type: str | None = None,
    folder: str = "",
    status: str | None = None,
    limit: int = 200,
) -> list[dict]:
    items = query_notes(
        index,
        status=status,
        frontmatter_filter={"type": type} if type else None,
        folder=folder,
        limit=limit,
    )
    out = []
    for item in items:
        fm = item.get("frontmatter") or {}
        aliases = fm.get("aliases") or []
        entry = {"path": item["path"], "title": item.get("title")}
        if fm.get("type"):
            entry["type"] = fm["type"]
        if item.get("status"):
            entry["status"] = item["status"]
        if aliases:
            entry["aliases"] = aliases if isinstance(aliases, list) else [aliases]
        out.append(entry)
    return out


# ── Log series ───────────────────────────────────────────────────────────────

_SERIES_LINE_RE = re.compile(r"^\s*[-*]\s+(\d{4}-\d{2}-\d{2})(?:[ T](\d{2}:\d{2}))?\s+(.*)$")
_SERIES_PAIR_RE = re.compile(r'([A-Za-z_][\w-]*)=(\[\[.*?\]\]|"[^"]*"|\S+)')
_SERIES_DEFAULT_LIMIT = 500


def _series_value(raw: str):
    if raw.startswith("[[") and raw.endswith("]]"):
        return raw[2:-2].split("|", 1)[0]
    if raw.startswith('"') and raw.endswith('"'):
        return raw[1:-1]
    for cast in (int, float):
        try:
            return cast(raw)
        except ValueError:
            pass
    return raw


def get_log_series(
    path: str,
    start: str | None = None,
    end: str | None = None,
    fields: list[str] | None = None,
    limit: int = _SERIES_DEFAULT_LIMIT,
) -> dict:
    """Parse a log note's `- YYYY-MM-DD[ HH:mm] key=value ...` lines into
    observations, oldest first. The Markdown stays the single source of truth:
    nothing is cached or written. Lines that do not start with a date are ignored.
    start/end are inclusive YYYY-MM-DD bounds; fields keeps only those keys."""
    for label, value in (("start", start), ("end", end)):
        if value is not None and not _DATE_RE.match(value):
            raise ValueError(f"{label} must be YYYY-MM-DD, got {value!r}.")
    note = read_note_content(path)
    wanted = set(fields) if fields else None
    seen: set[str] = set()
    items: list[dict] = []
    total = 0
    for line in note["content"].splitlines():
        m = _SERIES_LINE_RE.match(line)
        if not m:
            continue
        day, clock, rest = m.groups()
        if (start and day < start) or (end and day > end):
            continue
        item: dict = {"date": day}
        if clock:
            item["time"] = clock
        for key, raw in _SERIES_PAIR_RE.findall(rest):
            seen.add(key)
            if wanted is None or key in wanted:
                item[key] = _series_value(raw)
        total += 1
        if len(items) < limit:
            items.append(item)
    return {
        "path": path,
        "count": len(items),
        "matched": total,
        "truncated": total > len(items),
        "fields_available": sorted(seen),
        "items": items,
    }
